---
info:
  title: Metasploit Vagrant Builders
  description: Build tools to generate vagrant images used by metasploit-framework
    CI
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/metasploit-vagrant-builders
  x-cortex-tag: metasploit-vagrant-builders
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
